### ISSUE TITLE
Arbitrary time training

### ISSUE THREAD

**Issue by JiabenChen** [MCG-NJU/EMA-VFI#1]
Hi, congrats to your work! I wonder whether or when the training code supporting arbitrary time interpolation would be open-sourced? Thanks a lot!

**Comment by GuozhenZhang1999** [comment]
Thanks for your concern! We won't provide the training code that supports arbitrary temporal interpolation in order to reduce the complexity of the code base. But it should be noticed that the configuration of the training dataset is the only thing that needs to be changed (we follow the setting of [RIFE](https://github.com/megvii-research/ECCV2022-RIFE)); the rest of the training process is essentially the same for both fixed- and arbitrary-training.

**Comment by basilevh** [comment]
Hi,
It seems that RIFE doesn't have the arbitrary timestep handling in its train dataset loader either. Any chance you might be able to provide a reference implementation? I could do it myself but I want to ensure the setting is consistent (and it could presumably be beneficial for the research community at large as well).
Thank you very much in advance!
